### ISSUE TITLE
Remove API request requirement

### ISSUE THREAD

**Issue by roborourke** [humanmade/edgeo#1]
Currently a cold request to ip-api.com can take 500ms, once cached it's 5ms...

Ideally we should remove the need for any network requests, this could be done by having another lambda that has the maxmind GeoLite2 db locally, then we invoke that from the lambda@edge function.

**Comment by roborourke** [comment]
Ditched ip-api.com - using a 2 lambda solution instead

**Comment by rmccue** [comment]
What's better than 1 Lambda? 2 Lambdas!
